apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: jenkins-agent-role
  namespace: default
rules:
# Just an example, feel free to change it
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
